/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vivo_ai_service_process_CosineSimilarity */

#ifndef _Included_com_vivo_ai_service_process_CosineSimilarity
#define _Included_com_vivo_ai_service_process_CosineSimilarity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vivo_ai_service_process_CosineSimilarity
 * Method:    dd
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_vivo_ai_service_process_CosineSimilarity_dd___3F_3F
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     com_vivo_ai_service_process_CosineSimilarity
 * Method:    dd
 * Signature: (F[F[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_vivo_ai_service_process_CosineSimilarity_dd__F_3F_3F
  (JNIEnv *, jclass, jfloat, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
